server:
  port: 9999

spring:
#    mvc:
#        view:
#          prefix: /
#          suffix: .html
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/news?&useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: root
        password: 312ybj
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        # 最大激活链接
        maxActive: 20
        # 初始化连接数
        initialSize: 1
        # 最大等待数
        maxWait: 60000
        #  最小空闲
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        prefix: classpath:/static/
    http:
        multipart:
    redis:
        database: 1
        host: 192.168.0.58
        port: 6379
        password:
    mail:
        host: smtp.qq.com
        username: 352512524@qq.com
        password: hxervlfnzxascafd



mybatis:
  mapper-locations: classpath:com/lm/demo/mapper/*.xml
#  type-aliases-packag
e: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#mapper-locations: classpath:com/lm/demo/mapper/*.xml